Repository saltstack/salt-ext-modules-vmware, pull requests merged in 2022-09, with the labels that each got.

#295 quickstart typos
  docs/quickstart.rst
Labels: cla-not-required

#293 state module fuction for esxi set advanced config
  src/saltext/vmware/states/esxi.py
  tests/integration/conftest.py
  tests/integration/states/test_esxi.py
Labels: cla-rejected

#296 Esxi firewall config state
  src/saltext/vmware/modules/esxi.py
  src/saltext/vmware/states/esxi.py
  src/saltext/vmware/utils/esxi.py
  tests/integration/conftest.py
  tests/integration/states/test_esxi.py
Labels: cla-rejected

#298 Quickstart: Restored original example IP
  docs/quickstart.rst
Labels: cla-not-required

#304 Change docstrings from private addresses to documentation addresses
  src/saltext/vmware/modules/esxi.py
  src/saltext/vmware/modules/nsxt_policy_segment.py
  src/saltext/vmware/modules/nsxt_transport_node.py
  src/saltext/vmware/modules/vmc_dhcp_profiles.py
  src/saltext/vmware/modules/vmc_nat_rules.py
  src/saltext/vmware/modules/vmc_networks.py
  src/saltext/vmware/modules/vmc_security_groups.py
  src/saltext/vmware/states/nsxt_license.py
  src/saltext/vmware/states/nsxt_policy_segment.py
  src/saltext/vmware/states/nsxt_policy_tier0.py
  src/saltext/vmware/states/nsxt_transport_node.py
  src/saltext/vmware/states/vmc_dhcp_profiles.py
  src/saltext/vmware/states/vmc_nat_rules.py
  src/saltext/vmware/states/vmc_networks.py
  src/saltext/vmware/states/vmc_security_groups.py
Labels: cla-not-required

#303 release changes
  tools/release.py
Labels: cla-rejected

#258 Service instance profile configuration
  docs/credentials.rst
  docs/quickstart.rst
  src/saltext/vmware/modules/cluster.py
  src/saltext/vmware/modules/cluster_drs.py
  src/saltext/vmware/modules/cluster_ha.py
  src/saltext/vmware/modules/datacenter.py
  src/saltext/vmware/modules/datastore.py
  src/saltext/vmware/modules/dvswitch.py
  src/saltext/vmware/modules/esxi.py
  src/saltext/vmware/modules/folder.py
  src/saltext/vmware/modules/license_mgr.py
  src/saltext/vmware/modules/vm.py
  src/saltext/vmware/modules/vswitch.py
  src/saltext/vmware/states/datastore.py
  src/saltext/vmware/states/esxi.py
  src/saltext/vmware/states/folder.py
  src/saltext/vmware/states/nsxt_transport_node.py
  src/saltext/vmware/states/vm.py
  src/saltext/vmware/utils/connect.py
  tests/integration/conftest.py
Labels: needs-testcase
